### ISSUE TITLE
Changes to Insight API URL/response body

### ISSUE THREAD

**Issue by overheretoo** [PostHog/posthog-pagerduty-plugin#1]
PostHog version: Cloud - Free tier

It appears that there has been a change to the insights API URL, which means that `insightsApiUrl()` throws an error of 'not a valid trends URL'.

It isn't clear if/what parameters need to be passed with the new URL format to then satisfy `getTrend()` - using https://app.posthog.net/api/projects/<num>/insights does not appear to return data the function is expecting (TypeError).

**Comment by pauldambra** [comment]
Hey @overheretoo 

Thanks for your bug report. Could you provide reproduction steps or link to the methods you're referencing?

**Comment by pauldambra** [comment]
Hey @overheretoo 

Looking at that method https://github.com/PostHog/posthog-pagerduty-plugin/blob/main/index.js#L38

The API is read from the plugin config, and the referenced error message is thrown on this check https://github.com/PostHog/posthog-pagerduty-plugin/blob/main/index.js#L119 `!url.pathname.startsWith('/api/insight/trend')`

Can you confirm your configured URL and the full content of the error message you receive
